/*
 * File: TreeGridPanelTopToolBar.ui.js
 * Date: Fri Jul 23 2010 12:34:02 GMT+0800 (China Standard Time)
 * 
 * This file was generated by Ext Designer version xds-1.0.1.0c.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

TreeGridPanelTopToolBar = Ext.extend(Ext.Panel, {
    title: '',      
    layout: 'hbox',
    border: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: '',
                layout: 'table',
                border: false,
                flex: 1,
                autoWidth: false,
                autoHeight: false,
                layoutConfig: {
                    columns: 6
                },
                items: [
                    {
                        xtype: 'displayfield',
                        fieldLabel: 'Label',
                        value: '<p class="displayfield-font-grid-panel-top-toolbar">Campaign List<a href="#"><span>what&acute;s this?</span></a></p>',
                        colspan: 6,
                        width: 526
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Label',						
						fieldClass:'input-textfield',
						emptyText:'Enter Search'
                    },
                    {
                        xtype: 'button',
                        text: 'Go',
						cls:'btn btn-go-black'
                    },
                    {
                        xtype: 'label',
                        text: 'View:',
						cls:'label-font-grid-panel-top-toolbar-view'
			
                    },
                    {
						xtype: 'displayfield',
						itemCls:'',						
                        value: '<select class="select" name=""><option>All Unread Leads</option></select>'
                    },
                    {
                        xtype: 'button',
                        text: 'Go',
						cls:'btn btn-go-white'
                    },
                    {
                        xtype: 'displayfield',
                        fieldLabel: 'Label',
                        value: '<p class="link-font-grid-panel-top-toolbar"><a href="#">Edit</a><span> | </span><a href="#">Create New View</a></p>'
                    }
                ]
            },
            {
                xtype: 'panel',
                title: '',
                border: false,
                buttonAlign: 'right',
                flex: 1,           
                width:150,
				cls:'panel-createnew',
                items: [
                    {
                        xtype: 'button',
                       // text: 'MyButton',
						cls:'btn btn-createnew'
                    }
                ]
            }
        ];
        TreeGridPanelTopToolBar.superclass.initComponent.call(this);
    }
});
