/**
 * Ctrip JavaScript Code
 * http://www.ctrip.com/
 * Copyright(C) 2008 - 2015, Ctrip All rights reserved.
 * Version: 150115
 * Date: 2015-01-15
 */
;window.replace=function(){return ''};var Ctrip=Ctrip||{};Ctrip.Util={};Ctrip.Class={};Ctrip.Singleton={};Ctrip.Util.PageConfig={releaseNo:$("#_releaseNo_").value(),formValidate:$("#mailTxtId").regMod("validate","1.1")};Ctrip.Util.Extend=function(a,b){var h=function(){};h.prototype=b.prototype;a.prototype=new h;a.prototype.constructor=a;a.superclass=b.prototype};Ctrip.Util.loadJS=function(a,b){cQuery.loader.js(a,{type:"text/javascript",async:!0,charset:"utf-8",onload:b})};
Ctrip.Util.Animation={isRun:!1,anims:[],run:function(){var a=this,b=a.anims,h=setInterval(function(){var g=(new Date).getTime();if(0===b.length)clearInterval(h),a.isRun=!1;else for(var e=0;e<b.length;e++){var d=b[e].tFrom,f=d+b[e].time;(g>=d&&g<f?b[e].run():g>=f&&(b[e].runEnd(),b.splice(e,1)[0]))}},1)},add:function(a){this.isRun||(this.isRun=!0,this.run());a.run=function(){var b=a.styleFrom+(Number(new Date)-a.tFrom)/a.time*(a.styleTo-a.styleFrom),b=parseInt(b,10);this.setStyle(b)};a.runEnd=function(){this.setStyle(this.styleTo)};
a.setStyle=function(a){var h=this.obj,g=this.type;switch(g){case "opacity":h.style.opacity=a/100;h.style.filter="alpha(opacity="+a+")";break;default:h.style[g]=a+"px"}};this.anims.push(a);return a},stop:function(a){for(var b=this.anims,h=0;h<b.length;h++)a===b[h]&&b.splice(h,1)[0]}};Ctrip.Class.Form=function(a,b){this.form=a;this.submitBtn=b;this.v_methods=[];this.storage=null};Ctrip.Class.Form.prototype.regValidateMethod=function(a){this.v_methods.push(a)};
Ctrip.Class.Form.prototype.bindSubmit=function(){var a=this;this.submitBtn.bind("click",function(){for(var b=0,h=a.v_methods.length;b<h;b++)if(!a.v_methods[b]())return!1;a.setCookie();a.setPostValue();a.setAction();a.setStorage();a.form[0].submit();return!0})};Ctrip.Class.Form.prototype.setAction=function(){throw Error("\u62bd\u8c61\u65b9\u6cd5, \u4e0d\u80fd\u5b9e\u4f8b\u5316\u8c03\u7528\uff0c\u9700\u8981"+this.constructor+"\u5b50\u7c7b\u91cd\u5199");};
Ctrip.Class.Form.prototype.setPostValue=function(){throw Error("\u62bd\u8c61\u65b9\u6cd5, \u4e0d\u80fd\u5b9e\u4f8b\u5316\u8c03\u7528\uff0c\u9700\u8981"+this.constructor+"\u5b50\u7c7b\u91cd\u5199");};Ctrip.Class.Form.prototype.validateShow=function(a,b){Ctrip.Util.PageConfig.formValidate.method("show",{$obj:a,data:b,removeErrorClass:!0,hideEvent:"blur",isFocus:!0,isScroll:!1})};
Ctrip.Class.Form.prototype.setStorage=function(){throw Error("\u62bd\u8c61\u65b9\u6cd5, \u4e0d\u80fd\u5b9e\u4f8b\u5316\u8c03\u7528\uff0c\u9700\u8981"+this.constructor+"\u5b50\u7c7b\u91cd\u5199");};Ctrip.Class.Form.prototype.setCookie=function(){throw Error("\u62bd\u8c61\u65b9\u6cd5, \u4e0d\u80fd\u5b9e\u4f8b\u5316\u8c03\u7528\uff0c\u9700\u8981"+this.constructor+"\u5b50\u7c7b\u91cd\u5199");};
Ctrip.Class.Form.prototype.getStorage=function(){throw Error("\u62bd\u8c61\u65b9\u6cd5, \u4e0d\u80fd\u5b9e\u4f8b\u5316\u8c03\u7528\uff0c\u9700\u8981"+this.constructor+"\u5b50\u7c7b\u91cd\u5199");};Ctrip.Class.Form.prototype.setBtnEnable=function(){this.submitBtn[0].removeAttribute("disabled");this.submitBtn[0].className="s_btn"};Ctrip.Class.Form.prototype.setNotice=function(a,b,h){return a.regMod("notice","1.0",{name:b,tips:h,selClass:"inputSel"})};
Ctrip.Class.Form.prototype.regDateMod=function(a){return a.regMod("calendar","6.0",{options:{showWeek:!0,minDate:config.today}})};Ctrip.Class.Hotel=function(){this.chinaHotelJS=searchFile.chinaHotel;this.intHotelJS=searchFile.inteHotel;this.groupHotelJS=searchFile.groupHotel;this.hotelJJ=searchFile.hotel;this.isBindTabTab=this.intHotelJJJsLoad=this.intGroupHotelJsLoad=this.intHotelJsLoad=this.chinaHotelJsLoad=!1};
Ctrip.Class.Hotel.prototype.disHG=function(){var a=this;$("#groupHotelForm").css("display","block");$("#chinaHotelForm").css("display","none");$("#inteHotelForm").css("display","none");$("#hotelSwitch>a")[0].className="";$("#hotelSwitch>a")[1].className="";$("#hotelSwitch>a")[2].className="current";0<$("#Hotel_SSH_form").length&&($("#Hotel_SSH_form").css("display","none"),$("#hotelSwitch>a")[3].className="");(this.intGroupHotelJsLoad?window.initGroupHotel&&window.initGroupHotel():Ctrip.Util.loadJS(a.groupHotelJS,
function(){a.intGroupHotelJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Hotel.loadImg();window.initGroupHotel&&window.initGroupHotel()}));$.pageStorage.set("hotelTabStatus","groupHotel")};
Ctrip.Class.Hotel.prototype.disChina=function(){var a=this;$("#groupHotelForm").css("display","none");$("#chinaHotelForm").css("display","block");$("#inteHotelForm").css("display","none");$("#hotelSwitch>a")[0].className="current";$("#hotelSwitch>a")[1].className="";$("#hotelSwitch>a")[2].className="";0<$("#Hotel_SSH_form").length&&($("#Hotel_SSH_form").css("display","none"),$("#hotelSwitch>a")[3].className="");(this.chinaHotelJsLoad?window.chinaHotelSF&&window.chinaHotelSF():Ctrip.Util.loadJS(a.chinaHotelJS,
function(){a.chinaHotelJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Hotel.loadImg();Ctrip.Singleton.Flight.loadImg();window.chinaHotelSF&&window.chinaHotelSF()}));$.pageStorage.set("hotelTabStatus","china")};
Ctrip.Class.Hotel.prototype.disInt=function(){var a=this;$("#groupHotelForm").css("display","none");$("#chinaHotelForm").css("display","none");$("#inteHotelForm").css("display","block");$("#hotelSwitch>a")[0].className="";$("#hotelSwitch>a")[1].className="current";$("#hotelSwitch>a")[2].className="";0<$("#Hotel_SSH_form").length&&($("#Hotel_SSH_form").css("display","none"),$("#hotelSwitch>a")[3].className="");(this.intHotelJsLoad?window.inteHotelSF&&window.inteHotelSF():Ctrip.Util.loadJS(a.intHotelJS,
function(){a.intHotelJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Hotel.loadImg();Ctrip.Singleton.Flight.loadImg();window.inteHotelSF&&window.inteHotelSF()}));$.pageStorage.set("hotelTabStatus","inte")};
Ctrip.Class.Hotel.prototype.disHotelJJ=function(){var a=this;$("#groupHotelForm").css("display","none");$("#chinaHotelForm").css("display","none");$("#inteHotelForm").css("display","none");$("#hotelSwitch>a")[0].className="";$("#hotelSwitch>a")[1].className="";$("#hotelSwitch>a")[2].className="";0<$("#Hotel_SSH_form").length&&($("#Hotel_SSH_form").css("display","block"),$("#hotelSwitch>a")[3].className="current",(this.intHotelJJJsLoad?window.hotelJJSF&&window.hotelJJSF():Ctrip.Util.loadJS(a.hotelJJ,
function(){a.intHotelJJJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Hotel.loadImg();Ctrip.Singleton.Flight.loadImg();window.hotelJJSF&&window.hotelJJSF()})),$.pageStorage.set("hotelTabStatus","hotelJJ"))};
Ctrip.Class.Hotel.prototype.init=function(){var a=this;$.pageStorage.set("Tab",0);var b=$.pageStorage.get("hotelTabStatus")||"china";("china"===b?a.disChina():("inte"===b?a.disInt():("hotelJJ"===b?a.disHotelJJ():a.disHG())));b=$("#hotelSwitch>a");a.isBindTabTab||($(b[0]).bind("click",function(){a.disChina()}),$(b[1]).bind("click",function(){a.disInt()}),$(b[2]).bind("click",function(){a.disHG()}),4==b.length&&$(b[3]).bind("click",function(){a.disHotelJJ()}),a.isBindTabTab=!0)};
Ctrip.Class.Flight=function(){this.chinaFlightJS=searchFile.chinaFlight+"?"+$("#_releaseNo_").value();this.intFlightJS=searchFile.inteFlight+"?"+$("#_releaseNo_").value();this.isBindTabTab=this.intFlightJsLoad=this.chinaFlightJsLoad=!1};
Ctrip.Class.Flight.prototype.disChina=function(){var a=this;$("#fl_box_search").css("display","none");$("#FD_ChinaFlightForm").css("display","block");$("#flightSwitch>a")[0].className="current";$("#flightSwitch>a")[1].className="";(this.chinaFlightJsLoad?window.chinaFlightSF&&window.chinaFlightSF():Ctrip.Util.loadJS(a.chinaFlightJS,function(){a.chinaFlightJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Hotel.loadImg();Ctrip.Singleton.Flight.loadImg();window.chinaFlightSF&&window.chinaFlightSF()}));
$.pageStorage.set("isChinaFlightTab","true")};
Ctrip.Class.Flight.prototype.disInt=function(){var a=this;$("#FD_ChinaFlightForm").css("display","none");$("#flightSwitch>a")[0].className="";$("#fl_box_search").css("display","block");$("#flightSwitch>a")[1].className="current";(this.intFlightJsLoad?window.inteFlightSF&&window.inteFlightSF():Ctrip.Util.loadJS(a.intFlightJS,function(){a.intFlightJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Flight.loadImg();Ctrip.Singleton.Hotel.loadImg();window.inteFlightSF&&window.inteFlightSF()}));
$.pageStorage.set("isChinaFlightTab","false")};Ctrip.Class.Flight.prototype.init=function(){var a=this;$.pageStorage.set("Tab",1);("true"===($.pageStorage.get("isChinaFlightTab")||"true")?a.disChina():a.disInt());var b=$("#flightSwitch>a");a.isBindTabTab||($(b[0]).bind("click",function(){a.disChina()}),$(b[1]).bind("click",function(){setTimeout(function(){a.disInt()},50)}),a.isBindTabTab=!0)};Ctrip.Class.Free=function(){this.freeJS=searchFile.free+"?"+$("#_releaseNo_").value();this.isLoadFreeJS=!1};
Ctrip.Class.Free.prototype.init=function(){var a=this;$.pageStorage.set("Tab",2);(this.isLoadFreeJS?FHX.freeSF&&FHX.freeSF():Ctrip.Util.loadJS(a.freeJS,function(){a.isLoadFreeJS=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Flight.loadImg();Ctrip.Singleton.Hotel.loadImg();FHX.freeSF&&FHX.freeSF()}))};Ctrip.Class.Vacation=function(){this.vacationJS=searchFile.vacation+"?"+$("#_releaseNo_").value();this.isLoadVacationJS=!1};
Ctrip.Class.Vacation.prototype.init=function(){var a=this;$.pageStorage.set("Tab",3);(this.isLoadVacationJS?window.vacationSF&&window.vacationSF():Ctrip.Util.loadJS(a.vacationJS,function(){a.isLoadVacationJS=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Flight.loadImg();Ctrip.Singleton.Hotel.loadImg();window.vacationSF&&window.vacationSF()}))};Ctrip.Class.Train=function(){this.TrainJS=searchFile.train+"?"+$("#_releaseNo_").value();this.isLoadTrainJS=!1};
Ctrip.Class.Train.prototype.init=function(){var a=this;$.pageStorage.set("Tab",4);(this.isLoadTrainJS?window.trainSF&&window.trainSF():Ctrip.Util.loadJS(a.TrainJS,function(){a.isLoadTrainJS=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Flight.loadImg();Ctrip.Singleton.Hotel.loadImg();window.trainSF&&window.trainSF()}))};Ctrip.Class.Car=function(){this.CarJS=searchFile.car+"?"+$("#_releaseNo_").value();this.isBindTabTab=this.carJsLoad=!1};
Ctrip.Class.Car.prototype.disCarJie=function(){var a=this;$("#cs_chf").css("display","block");$("#cs_och").css("display","none");$("#cs_isd").css("display","none");$("#cs_osd").css("display","none");$("#carSwitch>a")[0].className="current";$("#carSwitch>a")[1].className="";$("#carSwitch>a")[2].className="";$("#carSwitch>a")[3].className="";this.carJsLoad||Ctrip.Util.loadJS(a.CarJS,function(){a.carJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Flight.loadImg();Ctrip.Singleton.Hotel.loadImg()});
$.pageStorage.set("carTabStatus","jie")};
Ctrip.Class.Car.prototype.disCarSong=function(){var a=this;$("#cs_chf").css("display","none");$("#cs_och").css("display","block");$("#cs_isd").css("display","none");$("#cs_osd").css("display","none");$("#carSwitch>a")[0].className="";$("#carSwitch>a")[1].className="current";$("#carSwitch>a")[2].className="";$("#carSwitch>a")[3].className="";this.carJsLoad||Ctrip.Util.loadJS(a.CarJS,function(){a.carJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Flight.loadImg();Ctrip.Singleton.Hotel.loadImg()});
$.pageStorage.set("carTabStatus","song")};
Ctrip.Class.Car.prototype.disCarOsd=function(){var a=this;$("#cs_chf").css("display","none");$("#cs_och").css("display","none");$("#cs_isd").css("display","block");$("#cs_osd").css("display","none");$("#carSwitch>a")[0].className="";$("#carSwitch>a")[1].className="";$("#carSwitch>a")[2].className="current";$("#carSwitch>a")[3].className="";this.carJsLoad||Ctrip.Util.loadJS(a.CarJS,function(){a.carJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Flight.loadImg();Ctrip.Singleton.Hotel.loadImg()});
$.pageStorage.set("carTabStatus","osd")};
Ctrip.Class.Car.prototype.disCarIsd=function(){var a=this;$("#cs_chf").css("display","none");$("#cs_och").css("display","none");$("#cs_isd").css("display","none");$("#cs_osd").css("display","block");$("#carSwitch>a")[0].className="";$("#carSwitch>a")[1].className="";$("#carSwitch>a")[2].className="";$("#carSwitch>a")[3].className="current";this.carJsLoad||Ctrip.Util.loadJS(a.CarJS,function(){a.carJsLoad=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Flight.loadImg();Ctrip.Singleton.Hotel.loadImg()});
$.pageStorage.set("carTabStatus","isd")};
Ctrip.Class.Car.prototype.init=function(){var a=this;$.pageStorage.set("Tab",5);var b=$.pageStorage.get("carTabStatus")||"jie";("jie"===b?a.disCarJie():("song"===b?a.disCarSong():("osd"===b?a.disCarOsd():a.disCarIsd())));b=$("#carSwitch>a");a.isBindTabTab||($(b[0]).bind("click",function(){a.disCarJie()}),$(b[1]).bind("click",function(){a.disCarSong()}),$(b[2]).bind("click",function(){a.disCarOsd()}),$(b[3]).bind("click",function(){a.disCarIsd()}),a.isBindTabTab=!0)};
Ctrip.Class.Ticket=function(){this.ticketJS=searchFile.ticket+"?"+$("#_releaseNo_").value();this.isLoadTicketJS=!1};Ctrip.Class.Ticket.prototype.init=function(){var a=this;$.pageStorage.set("Tab",6);(this.isLoadTicketJS?window.ticketSF&&window.ticketSF():Ctrip.Util.loadJS(a.ticketJS,function(){a.isLoadTicketJS=!0;Ctrip.Singleton.Vacation.loadImg();Ctrip.Singleton.Flight.loadImg();Ctrip.Singleton.Hotel.loadImg();window.ticketSF&&window.ticketSF()}))};
Ctrip.Singleton.Init=function(){$.mod.multiLoad({tab:"1.2",address:"1.0",calendar:"6.0",notice:"1.0",toggle:"1.0",validate:"1.1",allyes:"1.0",adFrame:"1.0",dropBox:"1.0"},function(){});if((/ip(hone|od)|ipad/i).test(navigator.userAgent)){$(document.body).css("cursor","pointer");var a;(document.all?(a=document.createStyleSheet(),a.cssText="*{-webkit-tap-highlight-color:rgba(0,0,0,0);}"):(a=document.createElement("style"),a.type="text/css",a.textContent="*{-webkit-tap-highlight-color:rgba(0,0,0,0);}"));
try{document.getElementsByTagName("head")[0].appendChild(a)}catch(b){}}String.prototype.replaceWith=function(a){return this.replace((/\{\$(\w+)\}/g),function(b,e){return (e in a?a[e]:b)})}}();
Ctrip.Singleton.BrowserHistory=function(){function a(){var c=$("#borwsing_list>li").length,a=0;4<=c&&(a=816-224*c,1180>document.body.clientWidth&&(a=816-224*(c+1)));c=$("#borwsing_list").css("left");(c.split("px")[0]-672>a?(g=c.split("px")[0]-672,$.mod.load("animate","1.0",function(){$("#borwsing_list").animate({left:g+"px"},"1000")})):(g=a,$.mod.load("animate","1.0",function(){$("#borwsing_list").animate({left:g+"px"},"1000")}),$("#a_movenext").removeClass().addClass("borwsing_next disabled")));$("#a_moveprev").removeClass().addClass("borwsing_prev")}
function b(){var c=$("#borwsing_list").css("left"),c=parseInt(c.split("px")[0]);0>c&&(g=c+672,0<g&&(g=0),$.mod.load("animate","1.0",function(){$("#borwsing_list").animate({left:g+"px"},"1000")}),0==g&&$("#a_moveprev").removeClass().addClass("borwsing_prev disabled"));$("#a_movenext").removeClass().addClass("borwsing_next")}function h(){$("#a_showordisplay").bind("click",function(){("block"==$("#browserHis_d").css("display")?($("#browserHis_d").css("display","none"),$("#browserHis_h").removeClass().addClass("borwsing_hd"),
$("#a_showordisplay").html("\u5c55\u5f00<i></i>"),$("#divKoubei").removeClass().addClass("tools_6"),$("#divKoubei").html("<i></i>\u643a\u7a0b\u65c5\u884c\u53e3\u7891\u699c"),$(".tools_11").css("display","none"),$(".tools_12").css("display","none")):($("#browserHis_d").css("display","block"),$("#browserHis_h").removeClass().addClass("borwsing_hd borwsing_hd_show"),$("#a_showordisplay").html("\u6536\u8d77<i></i>"),$("#divKoubei").removeClass().addClass("tools_7"),$("#divKoubei").html("<i></i>\u643a\u7a0b\u65c5\u884c\u53e3\u7891\u699c"),
$(".tools_11").css("display","block"),$(".tools_12").css("display","block")))});$("#a_movenext").bind("click",function(){a()});$("#a_movenext").bind("mouseout",function(){clearInterval(d)});$("#a_moveprev").bind("click",function(){b()});$("#a_moveprev").bind("mouseout",function(){clearInterval(d)})}var g=0,e=config.url.AjaxGetBrowserHistory,d,f={request:function(c,a){var k=this;$.ajax(c,{cache:!0,async:!0,method:cQuery.AJAX_METHOD_GET,onsuccess:function(c){(a?($(".tools_11").css("display","none"),$(".tools_12").css("display",
"none")):((c=$.parseJSON(c.responseText))&&0!==c.length?k.render(c):($("#browserHis_h").css("display","none"),$("#browserHis_d").css("display","none"),$(".tools_11").css("display","none"),$(".tools_12").css("display","none"))))}})},replaceWith:function(c,a){return c.replace((/\{\$(\w+)\}/g),function(c,f){return (f in a?a[f]:c)})},render:function(c){for(var a="",k="total="+c.length,b=0,d=c.length;b<d;b++){var g=b+1,a=a+f.replaceWith('<li class="{$css}" id="{$browserid}"><a href="{$imgclickurl}" class="borwsing_link" title="{$name}" target="_blank"><div class="b_thumb">{$img}</div><div class="b_name_single"><span title="{$name}">{$name}</span></div><span class="{$star}" title="{$title}"></span>{$price}<span class="b_tag">{$type}</span></a></li>',
{urlImg:c[b].url,url:c[b].url+"#ctm_ref=fav_chp_his_txt_"+g,imgclickurl:c[b].url+"#ctm_ref=fav_chp_his_img_"+g,title:c[b].title,price:c[b].price,star:c[b].star,img:c[b].img,name:c[b].name,type:c[b].type,css:c[b].css,browserid:"browserDetial_"+b,browserDelete:"browserDetial_"+b+"_Delete"});"hotel"==c[b].typeCode&&(k+="&prod"+g.toString()+"="+c[b].productID+"&chn"+g.toString()+"=htl");"flight"==c[b].typeCode&&(k+="&prod"+g.toString()+"="+c[b].productID+"&chn"+g.toString()+"=flt");"vaction"==c[b].typeCode&&
(k+="&prod"+g.toString()+"="+c[b].productID+"&chn"+g.toString()+"=vac");"ticket"==c[b].typeCode&&(k+="&prod"+g.toString()+"="+c[b].productID+"&chn"+g.toString()+"=vat")}$("#browserHis_h").css("display","block");$("#browserHis_d").css("display","block");b='<a id="a_movenext" href="javascript:;" class="borwsing_next"><i></i></a>';3>=c.length&&(b='<a id="a_movenext" href="javascript:;" class="borwsing_next disabled"><i></i></a>');4==c.length&&1180<=document.body.clientWidth&&(b='<a id="a_movenext" href="javascript:;" class="borwsing_next disabled"><i></i></a>');
$("#browserHis_d").html('<div class="borwsing_list_box"><ul class="borwsing_list" id="borwsing_list">'+a+'</div><a id="a_moveprev" href="javascript:;" class="borwsing_prev disabled"><i></i></a>'+b);$("#divKoubei").removeClass().addClass("tools_7");$("#divKoubei").html("<i></i>\u643a\u7a0b\u65c5\u884c\u53e3\u7891\u699c");$(".tools_11").css("display","block");$(".tools_12").css("display","block");document.getElementById("isShowChooseLanguage");"block"==document.getElementById("divChooseLanguage").style.display&&
$("#divChooseLanguage").mask();c=$("#browserHis_d")[0].getElementsByTagName("img");a=0;for(b=c.length;a<b;a++)c[a].getAttribute("_src")&&(c[a].src=c[a].getAttribute("_src"));h();window.__bfi.push(["_tracklog","chphisprod",k])}},e=e+"?r="+Math.random();f.request(e,!1)}();
Ctrip.Singleton.Deals=function(){var a=config.url.AjaxGetDeals,b=0,h=$("#v_departure>span")[0].getAttribute("cityId"),g={city:function(){$("#v_departure_city").bind("click",function(f){f=f||window.event;f=f.target||f.srcElement;"A"===f.nodeName&&0<$("#guessDeal_list").length&&"block"==$("#guessDeal_list").css("display")&&($("#v_departure>span")[0].innerHTML=f.innerHTML,$("#v_departure_city").css("display","none"),$("#v_departure")[0].className="startcity",h=f.getAttribute("data-id"),f=a+"?r="+Math.random()+
"&cityid="+h+"&type="+b,e.request(f,!1))})},tabtab:function(){var f=$("#guessPrdTypes");f[0].onclick=function(c){c=c||window.event;c=c.target||c.srcElement;if("A"===c.nodeName&&null!=c.getAttribute("data-id")){destCityPY=c.getAttribute("pinyin");$("#guessDeal_list>div:eq(1)").html('<div class="onloading"></div>');b=c.getAttribute("data-id");var q=a+"?r="+Math.random()+"&cityid="+h+"&type="+b;e.request(q,!1);f.find("a").removeClass("current");c.className="current"}}}},e={request:function(a,c){var b=
this;$.ajax(a,{cache:!0,async:!0,method:cQuery.AJAX_METHOD_GET,onsuccess:function(a){((a=$.parseJSON(a.responseText))?(0===a.length?c&&($("#deal_tab_guess").css("display","none"),$("#guessDeal_list").css("display","none"),$("#vacation_tab>span:eq(2)").click()):(b.render(a),g.tabtab())):c&&($("#deal_tab_guess").css("display","none"),$("#guessDeal_list").css("display","none"),$("#vacation_tab>span:eq(2)").click()))}})},replaceWith:function(a,c){return a.replace((/\{\$(\w+)\}/g),function(a,b){return (b in c?
c[b]:a)})},render:function(a){for(var c='<div class="vac_list"><div class="vac_item vac_item_main"><a target="_blank" href="{$PrdUrl}" class="link_box" title="{$PrdName}"><div class="vac_thumb" title="{$PrdName}"><img src="{$ImgUrl}" alt="{$PrdName}" width="500" height="280"></div><div class="vac_name">{$PrdName}{$Discount}</div><div class="vac_info"><del>\u00a5{$MarketPrice}</del>{$MinPrice}</div></a></div>'.replaceWith({PrdId:a.left.PrdId,PrdName:a.left.PrdName,PrdUrl:a.left.PrdUrl,ImgUrl:a.left.ImgUrl,
MinPrice:a.left.MinPrice,MarketPrice:a.left.MarketPrice,Discount:a.left.Discount}),b=[],k=0,d=a.right.length;k<d;k++)b[b.length]='<div class="vac_item"><a target="_blank" href="{$PrdUrl}" class="link_box" title="{$PrdName}"><div class="vac_thumb" title="{$PrdName}"><img src="{$ImgUrl}" alt="{$PrdName}" width="186" height="105"></div><div class="vac_name">{$PrdName}{$Discount}</div><div class="vac_info"><del>\u00a5{$MarketPrice}</del>{$MinPrice}</div></a></div>'.replaceWith({PrdId:a.right[k].PrdId,
PrdName:a.right[k].PrdName,PrdUrl:a.right[k].PrdUrl,ImgUrl:a.right[k].ImgUrl,MinPrice:a.right[k].MinPrice,MarketPrice:a.right[k].MarketPrice,Discount:a.right[k].Discount});$("#guessDeal_list").html(c+b.join(""));$("#guessDeal_list").css("display","block");$("#guessPrdTypes").css("display","block");$("#guessvacation_list").css("display","none");$("#vacation_tab_1,#vacation_tab_2,#vacation_tab_3,#vacation_tab_4,#vacation_tab_5,#vacation_tab_6").css("display","none");$("#vacation_list").css("display",
"none");$("#deal_tab_guess").css("display","block");$("#vacation_tab>span").removeClass("current");$("#vacation_tab")[0].getElementsByTagName("span")[1].className="current";a=$("#guessDeal_list")[0].getElementsByTagName("img");c=0;for(b=a.length;c<b;c++)a[c].getAttribute("_src")&&(a[c].src=a[c].getAttribute("_src"))}},d=a+"?r="+Math.random()+"&cityid="+h+"&type="+b;e.request(d,!0);g.city()}();
Ctrip.Singleton.Vacation=function(){var a=$("#v_departure>span")[0].getAttribute("cityId"),b=16,h=0,g=$("#vacation_tab_1>a")[0].getAttribute("pinyin"),e=config.url.vacationAjaxBI,d=0;currentTab="#vacation_tab_1";var f={dep:function(){$(document).bind("click",function(c){c=c||window.event;c=c.target||c.srcElement;$("#v_departure_city").contains(c)||"v_departure_city"===c.id||(($("#v_departure").contains(c)||"v_departure"===c.id?("none"===$("#v_departure_city").css("display")?($("#v_departure_city")[0].innerHTML+=
"",$("#v_departure")[0].className="startcity startcity_hover",$("#v_departure_city").css("display","block")):($("#v_departure")[0].className="startcity",$("#v_departure_city").css("display","none"))):($("#v_departure")[0].className="startcity",$("#v_departure_city").css("display","none"))))})},city:function(){$("#v_departure_city").bind("click",function(b){b=b||window.event;b=b.target||b.srcElement;if("SPAN"===b.nodeName&&"shortTab"===$(b).attr("el_type")){var k="#v_departure_city .city_item:eq("+$("#v_departure_city>ul>li").indexOf($(b).parentNode())+
")";$("#v_departure_city .hot_selected").removeClass("hot_selected");$(b).parentNode().addClass("hot_selected");$("#v_departure_city .city_item").css("display","none");$(k).css("display","block")}"A"===b.nodeName&&0<$("#vacation_list").length&&"block"==$("#vacation_list").css("display")&&($("#v_departure>span")[0].innerHTML=b.innerHTML,$("#v_departure_city").css("display","none"),$("#v_departure")[0].className="startcity",a=b.getAttribute("data-id"),g="",c.request(!1))})},refreshVacation:function(){0<
$("#vacation_fresh").length&&$("#vacation_fresh").bind("click",function(a){a=$("#guessVacationPageInfo").attr("guessVacationResult");c.render(a)})},tab:function(){for(var a=$("#vacation_tab")[0].getElementsByTagName("span"),k=0,f=a.length;k<f;k++)(function(k){$(a[k]).bind("click",function(){currentTab="#vacation_tab_"+(k-1);$("#vacation_tab>span").removeClass("current");$("#vacation_tab_1,#vacation_tab_2,#vacation_tab_3,#vacation_tab_4,#vacation_tab_5,#vacation_tab_6").css("display","none");a[k].className=
"current";$("#vacation_tab_"+(k-1)).css("display","block");b=a[k].getAttribute("data-id");g="";(0<$("#guessvacation_list").length?(0==k?($("#guessvacation_list").css("display","block"),$("#vacation_tab_1,#vacation_tab_2,#vacation_tab_3,#vacation_tab_4,#vacation_tab_5,#vacation_tab_6,#guessPrdTypes").css("display","none"),$("#vacation_list").css("display","none"),$("#v_departCity").css("display","none"),$("#guessDeal_list").css("display","none"),$("#guessPrdTypes").css("display","none")):(1==k?($("#guessvacation_list").css("display",
"none"),$("#vacation_list").css("display","none"),$("#v_departCity").css("display","block"),$("#vacation_tab_1,#vacation_tab_2,#vacation_tab_3,#vacation_tab_4,#vacation_tab_5,#vacation_tab_6").css("display","none"),$("#guessDeal_list").css("display","block"),$("#guessPrdTypes").css("display","block")):((5==k?($("#guessvacation_list").css("display","none"),$("#guessDeal_list").css("display","none"),$("#vacation_list").css("display","block"),$("#v_departCity").css("display","none")):($("#guessvacation_list").css("display",
"none"),$("#guessDeal_list").css("display","none"),$("#vacation_list").css("display","block"),$("#v_departCity").css("display","block"))),$("#guessPrdTypes").css("display","none"),c.request(!1)))):(0<$("#guessDeal_list").length?(1==k?($("#guessvacation_list").css("display","none"),$("#vacation_tab_1,#vacation_tab_2,#vacation_tab_3,#vacation_tab_4,#vacation_tab_5,#vacation_tab_6").css("display","none"),$("#guessDeal_list").css("display","block"),$("#vacation_list").css("display","none"),$("#v_departCity").css("display",
"block"),$("#guessPrdTypes").css("display","block")):((5==k?($("#guessvacation_list").css("display","none"),$("#guessDeal_list").css("display","none"),$("#vacation_list").css("display","block"),$("#v_departCity").css("display","none")):($("#guessvacation_list").css("display","none"),$("#guessDeal_list").css("display","none"),$("#vacation_list").css("display","block"),$("#v_departCity").css("display","block"))),$("#guessPrdTypes").css("display","none"),c.request(!1))):c.request(!1)))})})(k)},tabtab:function(){function a(b){b.bind("click",
function(a){a=a||window.event;a=a.target||a.srcElement;if("more"===a.className){var f=a.parentNode.getElementsByTagName("div")[0];f.innerHTML+="";("none"===f.style.display?(f.style.display="block",a.parentNode.className="city_pop city_pop_hover"):(f.style.display="none",a.parentNode.className="city_pop"))}else if("A"===a.nodeName){if("morecity"===a.parentNode.className){a.parentNode.style.display="none";a.parentNode.parentNode.className="city_pop";var f=a.parentNode.parentNode.parentNode,d=$(f).find("a[class=current]");
0<d.length&&(d[0].className="");f=$("#"+f.id+">a");f=f[f.length-1];d=a.cloneNode(!0);d.className="current";f.parentNode.replaceChild(d,f);f.className="";a.parentNode.replaceChild(f,a);g=a.getAttribute("pinyin")}else g=a.getAttribute("pinyin"),f=b.find("a"),f.removeClass("current"),a.className="current";$("#vacation_list").html('<div class="onloading"></div>');c.request(!0)}})}a($("#vacation_tab_1"));a($("#vacation_tab_2"));a($("#vacation_tab_3"));a($("#vacation_tab_4"));a($("#vacation_tab_5"));a($("#vacation_tab_6"));
$(document).bind("click",function(a){a=a||window.event;a=a.target||a.srcElement;var c=$("#vacation_tab_1>div"),b=$("#vacation_tab_2>div"),f=$("#vacation_tab_3>div"),d=$("#vacation_tab_4>div"),g=$("#vacation_tab_5>div");disT6=$("#vacation_tab_6>div");0<c.length&&!c[0].contains(a)&&(c[0].getElementsByTagName("div")[0].style.display="none",c[0].className="city_pop");0<b.length&&!b[0].contains(a)&&(b[0].getElementsByTagName("div")[0].style.display="none",b[0].className="city_pop");0<f.length&&!f[0].contains(a)&&
(f[0].getElementsByTagName("div")[0].style.display="none",f[0].className="city_pop");0<d.length&&!d[0].contains(a)&&(d[0].getElementsByTagName("div")[0].style.display="none",d[0].className="city_pop");0<g.length&&!g[0].contains(a)&&(g[0].getElementsByTagName("div")[0].style.display="none",g[0].className="city_pop");0<disT6.length&&!disT6[0].contains(a)&&(disT6[0].getElementsByTagName("div")[0].style.display="none",disT6[0].className="city_pop")})}},c={request:function(c){var f=this;$.ajax(e,{cache:!0,
async:!0,method:cQuery.AJAX_METHOD_POST,context:{startCityId:a,tabId:b,destCity:g},onsuccess:function(a){a=$.parseJSON(a.responseText);f.formatHTML(c,a)}})},guessRequest:function(c){if(0>=$("#guessvacation_list").length)$("#vacation_tab>span").removeClass("current"),$("#vacation_tab")[0].getElementsByTagName("span")[1].className="current";else{var b=this;$.ajax(c,{cache:!0,async:!0,method:cQuery.AJAX_METHOD_POST,context:{startCityId:a,destCity:g,guessIndex:h},onsuccess:function(a){var c=$.parseJSON(a.responseText);
(c?(0===c.jsonArr.length?($("#guessvacation_list").css("display","none"),$("#vacation_tab_guess").css("display","none"),$("#vacation_tab")[0].getElementsByTagName("span")[1].className="current"):b.render(c,a.responseText)):($("#guessvacation_list").css("display","none"),$("#vacation_tab_guess").css("display","none"),$("#vacation_tab")[0].getElementsByTagName("span")[1].className="current"))}})}},render:function(a,b){var f='<span class="i_switch" id="vacation_fresh"><i></i>\u6362\u4e00\u6279</span><ul class="likes_vac_list">',
g;tracevalue="";var e=0,e=a.pageInfo.guessVacationAmounts;tracevalue="total="+e.toString()+"&chgnum="+d.toString();10>e&&(f='<ul class="likes_vac_list">');g='<span id="guessVacationPageInfo" guessVacationAmounts ={$guessVacationAmounts}><script type="text/plain" id="vacationresponseText">{$guessVacationResult}\x3c/script></span>'.replaceWith({guessVacationAmounts:e,guessVacationResult:b});e=parseInt(e/5);h>e-1&&(h=0);var e=a.jsonArr[h],p='<li class="likes_vac_main"><a target="_blank" class="link_box" href="{$imgclickurl}" title="{$name}"><div class="vac_thumb"><img _src="{$image}" height="270" alt="{$name}"></div>{$youhui}<div class="vac_name">{$name}</div><div class="vac_info">{$price}{$jian}{$fan}</div></a></li>'.replaceWith({name:e.left.name,
image:e.left.image,url:e.left.url+"#ctm_ref=fav_chp_gsp_txt_1",imgclickurl:e.left.url+"#ctm_ref=fav_chp_gsp_img_1",price:e.left.price,youhui:e.left.youhui,jian:e.left.jian,fan:e.left.fan});tracevalue+="&prod1="+e.left.productID+"&rstype1=r"+e.left.rank;tracevalue=("1"==e.left.rec?tracevalue+"&bztype1=rec":tracevalue+"&bztype1=hot");for(var m=[],n=0,s=e.right.length;n<s;n++){var r=n+2;m[m.length]='<li><a target="_blank" href="{$imgclickurl}" class="link_box" title="{$name}"><div class="vac_thumb"><img _src="{$image}" width="200" alt="{$name}"></div>{$youhui}<div class="vac_name">{$name}</div><div class="vac_info">{$price}{$jian}{$fan}</div></a></li>'.replaceWith({name:e.right[n].name,
image:e.right[n].image,url:e.right[n].url+"#ctm_ref=fav_chp_gsp_txt_"+r,imgclickurl:e.right[n].url+"#ctm_ref=fav_chp_gsp_img_"+r,price:e.right[n].price,youhui:e.right[n].youhui,jian:e.right[n].jian,fan:e.right[n].fan});tracevalue+="&prod"+r.toString()+"="+e.right[n].productID+"&rstype"+r.toString()+"=r"+e.right[n].rank;tracevalue=("1"==e.right[n].rec?tracevalue+("&bztype"+r.toString()+"=rec"):tracevalue+("&bztype"+r.toString()+"=hot"))}$("#guessvacation_list").html(f+g+p+m.join("")+"</ul>");$("#guessvacation_list").css("display",
"block");$("#guessvacation_list").addClass("fade_in");$("#vacation_tab_guess").css("display","block");$("#vacation_tab_1,#vacation_tab_2,#vacation_tab_3,#vacation_tab_4,#vacation_tab_5,#vacation_tab_6").css("display","none");$("#guessDeal_list").css("display","none");$("#guessPrdTypes").css("display","none");$("#vacation_list").css("display","none");$("#v_departCity").css("display","none");$("#vacation_tab>span").removeClass("current");$("#vacation_tab")[0].getElementsByTagName("span")[0].className=
"current";$("#vacation_fresh").bind("click",function(a){h+=1;d+=1;a=$("#vacationresponseText").html();var b=$.parseJSON(a);c.render(b,a)});c.lazyLoad();window.__bfi.push(["_tracklog","pub.yy.chprsvac",tracevalue])},formatHTML:function(a,c){for(var b=[],f=[],d=0,e=c.destCity.length;d<e;d++)(0===d?b[0]='<a class="current" pinyin="{$pinyin}" href="{$url}">{$name}</a>'.replaceWith({pinyin:c.destCity[d].pinyin,name:c.destCity[d].name,url:(c.destCity[d][2]?c.destCity[d][2]:"javascript:void(0);")}):(7<=d?f[f.length]=
'<a pinyin="{$pinyin}" href="{$url}">{$name}</a>'.replaceWith({pinyin:c.destCity[d].pinyin,name:c.destCity[d].name,url:(c.destCity[d][2]?c.destCity[d][2]:"javascript:void(0);")}):b[b.length]='<a pinyin="{$pinyin}" href="{$url}">{$name}</a>'.replaceWith({pinyin:c.destCity[d].pinyin,name:c.destCity[d].name,url:(c.destCity[d][2]?c.destCity[d][2]:"javascript:void(0);")})));for(var g='<div class="vac_list"><div class="vac_item vac_item_main"><a target="_blank" href="{$url}" class="link_box" title ="{$name}"><div class="vac_thumb" title="{$name}"><img src="{$image}" alt="" width="500" height="280" /></div><div class="vac_name">{$name}</div><div class="vac_info">{$price}</div></a></div>'.replaceWith({name:c.left.name,
image:c.left.image,url:c.left.url,price:c.left.price}),h=[],d=0,e=c.right.length;d<e;d++)h[h.length]='<div class="vac_item"><a target="_blank" href="{$url}" class="link_box" title ="{$name}"><div class="vac_thumb"><img src="{$image}" alt="" width="186" height="105" /></div><div class="vac_name">{$name}</div><div class="vac_info">{$price}</div></a></div>'.replaceWith({name:c.right[d].name,image:c.right[d].image,url:c.right[d].url,price:c.right[d].price});a||(d='<div class="city_pop">                        <a class="more" href="javascript:void(0)">\u66f4\u591a</a>                        <div class="morecity" style="display:none;width:82px;">                        {$a7}                        </div>                        </div>'.replaceWith({a7:f.join("")}),
(0<f.length?$(currentTab).html(b.join("")+d):$(currentTab).html(b.join(""))),destCity=$(currentTab).find("a")[0].innerHTML);$("#vacation_list").html(g+h.join(""));Ctrip.Singleton.Statistic.setVacationStat()},lazyLoad:function(){for(var c=$("#vacation_list")[0].getElementsByTagName("img"),a=0,b=c.length;a<b;a++)c[a].getAttribute("_src")&&(c[a].src=c[a].getAttribute("_src"));c=$("#guessvacation_list")[0].getElementsByTagName("img");a=0;for(b=c.length;a<b;a++)c[a].getAttribute("_src")&&(c[a].src=c[a].getAttribute("_src"))}};
f.tab();f.tabtab();f.dep();f.city();c.guessRequest(e);return{loadImg:function(){c.lazyLoad()}}}();
Ctrip.Singleton.Hotel=function(){var a=1,b=2,h=config.url.hotelAjaxBI,g=0,e=0,d={moreCity:function(){$("#hotelCityPop").bind("click",function(c){c=c||window.event;"more"===(c.target||c.srcElement).className&&(("none"===$("#hotelMoreCity").css("display")?($("#hotelMoreCity")[0].style.display="block",$("#hotelMoreCity")[0].innerHTML+="",$("#hotelCityPop")[0].className="city_pop city_pop_hover"):($("#hotelMoreCity")[0].style.display="none",$("#hotelCityPop")[0].className="city_pop")))});$(document).bind("click",
function(c){c=c||window.event;c=c.target||c.srcElement;$("#hotelCityPop").contains(c)||($("#hotelMoreCity")[0].style.display="none",$("#hotelCityPop")[0].className="city_pop")});$("#hotelMoreCity").bind("mousedown",function(c){c=c||window.event;c=c.target||c.srcElement;if("A"===c.nodeName){$("#hotelCityPop")[0].className="city_pop";b=c.getAttribute("data-id");a=c.getAttribute("data-type");$("#hotelMoreCity").css("display","none");f.request();var d=$("#hotelCityTab>a[class=current]");0<d.length&&(d[0].className=
"");var d=$("#hotelCityTab>a"),d=d[d.length-1],e=c.cloneNode(!0);e.className="current";d.parentNode.replaceChild(e,d);d.className="";var e=d.getAttribute("data-type"),g=document.getElementById("hotelMoreLine");("1"===e?document.getElementById("hotelMoreCity").insertBefore(d,g):c.parentNode.appendChild(d));c.parentNode.removeChild(c);setTimeout(function(){var c=$("#hotelCityTab>a");c[c.length-1].className="current"},100);$("#hotelMoreCity")[0].innerHTML+=""}})},refreshHotel:function(){0<$("#hotel_fresh").length&&
$("#hotel_fresh").bind("click",function(c){f.guessRequest(h)})},overtab:function(){$("#hotel_tab").bind("mousedown",function(c){$("#guessHotelListId>ul")[0]&&($("#hotel_tab")[0].getElementsByTagName("span"),c=c||window.event,c=c.target||c.srcElement,"hotel_tab_2"==c.id&&($("#guessHotelListId").css("display","none"),$("#hotelCityTab").css("display","block"),$("#hotelListId").css("display","block"),$("#hotelListId_f").css("display","block"),$("#hotel_tab>span").removeClass("current"),$("#hotel_tab>span")[1].className=
"current"),"hotel_tab_1"==c.id&&($("#guessHotelListId").css("display","block"),$("#hotelCityTab").css("display","none"),$("#hotelListId").css("display","none"),$("#hotelListId_f").css("display","none"),$("#hotel_tab>span").removeClass("current"),$("#hotel_tab>span")[0].className="current"))})},tab:function(){$("#hotelCityTab").bind("mousedown",function(c){c=c||window.event;c=c.target||c.srcElement;"more"!==c.className&&"A"===c.nodeName&&c.parentNode&&(c.href="###",$("#hotelCityTab>a").removeClass("current"),
c.className="current",b=c.getAttribute("data-id"),a=c.getAttribute("data-type"),f.request())})}},f={request:function(){var c=this;$.ajax(h,{cache:!0,async:!0,method:cQuery.AJAX_METHOD_POST,context:{tabId:a,cityId:b},onsuccess:function(a){a=$.parseJSON(a.responseText);c.formatHTML(a)}})},guessRequest:function(c){var b=this;$.ajax(c,{cache:!0,async:!0,method:cQuery.AJAX_METHOD_POST,context:{tabId:a,guessIndex:g},onsuccess:function(c){var a=$.parseJSON(c.responseText);(a?b.render(a,c.responseText):($("#guessHotelListId").css("display",
"none"),$("#hotel_tab_1").css("display","none"),$("#hotelCityTab").css("display","block"),$("#hotelListId").css("display","block"),$("#hotelListId_f").css("display","block"),$("#hotel_tab>span").removeClass("current"),$("#hotel_tab>span")[1].className="current"))}})},render:function(c,a){var b='<span class="i_switch" id="hotel_fresh"><i></i>\u6362\u4e00\u6279</span><ul class="likes_hotel_list">',d=0,d=c.pageInfo.guessHotelAmounts,h="total="+d.toString()+"&chgnum="+e.toString(),u='<span id="guessHotelPageInfo" guessHotelAmounts ={$guessHotelAmounts}></span><script type="text/plain" id="hotelresponseText">{$guessHotelResult}\x3c/script>'.replaceWith({guessHotelAmounts:d,
guessHotelResult:a});8>d&&(b='<ul class="likes_hotel_list">');d=parseInt(d/4);g>d-1&&(g=0);for(var d=c.jsonArr[g],p=[],m=0,n=d.length;m<n;m++){var s=m+1,r=d[m].commentAmount,v=d[m].pingfen;p[p.length]='<li><a target="_blank" href="{$imgclickurl}" class="hotel_thumb" title="{$hotelName}" target="_blank"><img _src="{$picUrl}" alt="{$hotelName}"></a><div class="hotel_name"><a target="_blank" href="{$hotelurl}" title="{$hotelName}">{$hotelName}</a></div><span class="{$diamondCSS}"></span><div class="hotel_area">{$zoneName}{$zone2Name}</div><div class="hotel_price_box">{$minPrice}</div><a href="{$dpUrl}" class="hotel_comment" target="blank">{$comment}</a></li>'.replaceWith({hotelurl:d[m].hotelurl+
"#ctm_ref=fav_chp_gsh_txt_"+s,imgclickurl:d[m].hotelurl+"#ctm_ref=fav_chp_gsh_img_"+s,medalCSS:d[m].medalCSS,medalTitle:d[m].medalTitle,hotelName:d[m].hotelName,picUrl:d[m].picUrl,logUrl:d[m].logoUrl+"#ctm_ref=fav_chp_gsh_txt_"+s,diamondCSS:d[m].diamondCSS,diamondTitle:d[m].diamondTitle,locationName:d[m].locationName,zoneName:d[m].zoneName,zone2Name:d[m].zone2Name,zoneUrl:d[m].zoneUrl,zone2Url:d[m].zone2Url,location:d[m].location,minPrice:d[m].minPrice,dpUrl:d[m].dpUrl,comment:(0===r||"0"===v?"\u6682\u65e0\u70b9\u8bc4":
"<em>"+v+"</em>\u5206 <span>"+r+"\u4eba\u70b9\u8bc4</span>")});h+="&prod"+s.toString()+"="+d[m].hotelID}$("#guessHotelListId").html(b+u+p.join("")+"</ul>");$("#guessHotelListId").css("display","block");$("#guessHotelListId").addClass("fade_in");$("#hotel_tab_1").css("display","block");$("#hotelCityTab").css("display","none");$("#hotelListId").css("display","none");$("#hotelListId_f").css("display","none");$("#hotel_tab>span").removeClass("current");$("#hotel_tab>span")[0].className="current";$("#hotel_fresh").bind("click",
function(c){c=$("#hotelresponseText").html();g+=1;e+=1;var a=$.parseJSON(c);f.render(a,c)});f.lazyLoad();window.__bfi.push(["_tracklog","pub.yy.chprshtl",h])},formatHTML:function(c){for(var a=[],b=0,d=c.hotel.length;b<d;b++){var f=c.hotel[b].commentAmount,e=c.hotel[b].customEval;a[a.length]='<dl class="hotel_item">                        <dt><span class="{$medalCSS}" title="{$medalTitle}"></span><a target="_blank" href="{$url}" title="{$hotelName}">{$hotelName}</a></dt>                        <dd class="hotel_thumb"><a target="_blank" href="{$picUrl}"><img alt="{$hotelName}" src="{$logUrl}" width="130" height="130" /></a></dd>                        <dd><span class="{$diamondCSS}" title="{$diamondTitle}"></span></dd>                        <dd class="hotel_item_area">{$zone}{$zone2}{$location}</dd>                        <dd class="hotel_info">                            <span class="c_price">{$minPrice}</span>\u8d77                        </dd>                        <dd class="hotel_comment"><a target="_blank" href="{$dpUrl}">{$comment}</a></dd>                    </dl>'.replaceWith({url:c.hotel[b].hotelurl,
medalCSS:c.hotel[b].medalCSS,medalTitle:c.hotel[b].medalTitle,hotelName:c.hotel[b].hotelName,picUrl:c.hotel[b].picUrl,logUrl:c.hotel[b].logoUrl,diamondCSS:c.hotel[b].diamondCSS,diamondTitle:c.hotel[b].diamondTitle,locationName:c.hotel[b].locationName,zone:c.hotel[b].zone,zone2:c.hotel[b].zone2,location:c.hotel[b].location,minPrice:c.hotel[b].minPrice,dpUrl:c.hotel[b].dpUrl,comment:(0===f||"0"===e?"\u6682\u65e0\u70b9\u8bc4":"<b>"+e+"</b>\u5206 | "+f+"\u4eba\u70b9\u8bc4")})}$("#hotelListId").html(a.join(""));
Ctrip.Singleton.Statistic.setHotelStat()},lazyLoad:function(){for(var c=$("#hotelListId")[0].getElementsByTagName("img"),a=0,b=c.length;a<b;a++)c[a].getAttribute("_src")&&(c[a].src=c[a].getAttribute("_src"));c=$("#guessHotelListId")[0].getElementsByTagName("img");a=0;for(b=c.length;a<b;a++)c[a].getAttribute("_src")&&(c[a].src=c[a].getAttribute("_src"))}};d.moreCity();d.tab();d.overtab();d.refreshHotel();f.guessRequest(h);return{loadImg:function(){f.lazyLoad()}}}();
Ctrip.Singleton.Tab=function(){var a=new Ctrip.Class.Hotel,b=new Ctrip.Class.Flight,h=new Ctrip.Class.Free,g=new Ctrip.Class.Vacation,e=new Ctrip.Class.Train,d=new Ctrip.Class.Car,f=new Ctrip.Class.Ticket,c=function(a){$.ajax("http://"+window.location.host+"/homepage/Tool/AjaxGetLastSavedSearch.ashx",{onsuccess:function(c){c=c.response;("hotel"==c||"intlhotel"==c?($.pageStorage.set("Tab",0),("hotel"==c?$.pageStorage.set("hotelTabStatus","china"):$.pageStorage.set("hotelTabStatus","inte")),a.set("index",
0)):("flt"==c||"fltintl"==c?($.pageStorage.set("Tab",1),("flt"==c?$.pageStorage.set("isChinaFlightTab","true"):$.pageStorage.set("isChinaFlightTab","false")),a.set("index",1)):a.set("index",0)))},onerror:function(){a.set("index",0)}})},q=$("#searchBox").regMod("tab","1.2",{options:{index:0,tab:"li",panel:"#searchBox>div",save:!1},style:{tab:["s_tab_current","s_tab_nocurrent"],panel:{display:["","none"]}},listeners:{initEventCallback:function(){$("#searchBoxUl").css("visibility","")},returnTab:function(c,
q){switch(q.getAttribute("styleTag")){case "hotel":a.init();break;case "flight":b.init();break;case "free":h.init();break;case "vacation":g.init();break;case "train":e.init();break;case "car":d.init();break;case "ticket":f.init()}}}});($.pageStorage.get("Tab")?q.set("index",$.pageStorage.get("Tab")):c(q));Ctrip.Util.loadJS(advertiseIds,function(){})}();
Ctrip.Singleton.TabInitSize=function(){function a(a){var c=a.replace("china_","").replace("int_","");$("#searchBox")[0].className=g[a].classes;$("#searchBox").css("width",g[a].outWidth+"px");$("#searchBox").css("height",g[a].outHeight+"px");$("#searchBox>div[styleTag="+c+"]").css("width",g[a].innerWidth+"px");$("#searchBox>div[styleTag="+c+"]").css("height",g[a].innerHeight+"px");$("#searchBox>ul").css("height",g[a].ulHeight+"px")}function b(a){var c=a.replace("china_","").replace("int_","");g[a]=
{classes:$("#searchBox")[0].className,outWidth:$("#searchBox")[0].offsetWidth-14,outHeight:$("#searchBox")[0].offsetHeight-14,innerWidth:$("#searchBox>div[styleTag="+c+"]")[0].offsetWidth-41,innerHeight:$("#searchBox>div[styleTag="+c+"]")[0].offsetHeight-25,ulHeight:$("#searchBox>ul")[0].offsetHeight}}var h={classes:"searchbox",outWidth:"566",outHeight:"286",innerWidth:"451",innerHeight:"261",ulHeight:"286"},g={china_hotel:h,int_hotel:h,china_flight:h,int_flight:h,free:h,vacation:h,ticket:h,you:h,
mobilePhone:h,train:h,car:h};$("#searchBox>ul").bind("mousedown",function(){var a=$("#searchBox>ul>li[class=s_tab_current]")[0].getAttribute("styleTag");a&&""!==a&&(("hotel"===a?(a=$("#hotelSwitch>a")[0].className,("current"===a?b("china_hotel"):b("int_hotel"))):("flight"===a?(a=$("#flightSwitch>a")[0].className,("current"===a?b("china_flight"):b("int_flight"))):b(a))))});var e=$("#hotelSwitch>a");$(e[0]).bind("mousedown",function(){"current"!==e[0].className&&(b("int_hotel"),a("china_hotel"))});$(e[1]).bind("mousedown",
function(){"current"===e[0].className&&(b("china_hotel"),a("int_hotel"))});var d=$("#flightSwitch>a");$(d[0]).bind("click",function(){"current"!==d[0].className&&(b("int_flight"),a("china_flight"))});$(d[1]).bind("click",function(){"current"===d[0].className&&(b("china_flight"),setTimeout(function(){a("int_flight")},50))});$("#searchBox>ul>li").bind("click",function(){var b=this.getAttribute("styleTag");("hotel"===b?(b=$("#hotelSwitch>a")[0].className,("current"===b?a("china_hotel"):a("int_hotel"))):
("flight"===b?(b=$("#flightSwitch>a")[0].className,("current"===b?a("china_flight"):a("int_flight"))):a(b)))})}();
Ctrip.Singleton.Statistic=function(){var a=function(){for(var a=$("#vacation_list>div>a[class=vac_thumb]"),b=$("#vacation_list>div>a[class!=vac_thumb]"),d=0,f=a.length;d<f;d++){var c=a[d].href.split("#")[0];a[d].href=c+"#ctm_ref=chp_vac_"+(d+1)+"_i"}d=0;for(f=b.length;d<f;d++)c=b[d].href.split("#")[0],b[d].href=c+"#ctm_ref=chp_vac_"+(d+1)+"_n"},b=function(){for(var a=$("#hotelListId>dl>dd[class=hotel_thumb]>a"),b=$("#hotelListId>dl>dt>a"),d=$("#hotelListId>dl>dd[class=hotel_comment]>a"),f=$("#hotelListId>dl>dd[class=hotel_item_area]"),
c=0,h=a.length;c<h;c++){var k=a[c].href.split("#")[0];a[c].href=k+"#ctm_ref=chp_htl_"+(c+1)+"_i"}c=0;for(h=b.length;c<h;c++)k=b[c].href.split("#")[0],b[c].href=k+"#ctm_ref=chp_htl_"+(c+1)+"_n";c=0;for(h=d.length;c<h;c++)k=d[c].href.split("#")[0],d[c].href=k+"#ctm_ref=chp_htl_"+(c+1)+"_c";c=0;for(h=f.length;c<h;c++)a=f[c].getElementsByTagName("a"),"undefined"!==typeof a[0]&&(b=a[0].href.split("#")[0],a[0].href=b+"#ctm_ref=chp_htl_"+(c+1)+"_z"),"undefined"!==typeof a[1]&&(b=a[1].href.split("#")[0],
a[1].href=b+"#ctm_ref=chp_htl_"+(c+1)+"_l")},h=function(){try{for(var a=$("#flightList>dl"),b=0,d=a.length;b<d;b++)(function(){var c=b,d=a[b].getAttribute("onclick"),f=("function"===typeof d?(d+"").split("('")[1].split("');")[0]:d.split("('")[1].split("');")[0]),f=f+"#ctm_ref= chp_flt_"+(c+1)+"_p";a[b].onclick=function(){window.open(f)}})(b);for(var f=$("#flightList>dl>dt>a"),b=0,d=f.length;b<d;b++){var c=f[b].href.split("#")[0];f[b].href=c+"#ctm_ref=chp_flt_"+(b+1)+"_n"}}catch(h){}};$("#flightList").bind("mousedown",
function(a){a=a.target||window.event.srcElement;"A"===a.nodeName&&(a.href="javascript:void(0)")});a();b();h();return{setVacationStat:function(){a()},setHotelStat:function(){b()},setFlightStat:function(){h()}}}();
Ctrip.Singleton.Flight=function(){var a="SHY",b=config.url.flightAjax,h=0,g={moreCity:function(){$("#packageRecommend").bind("click",function(){$("#flightMoreCityDiv")[0].innerHTML+="";("none"===$("#flightMoreCityDiv").css("display")?($("#flightMoreCityDiv").css("display","block"),$("#packageRecommend")[0].className="startcity startcity_hover"):($("#flightMoreCityDiv").css("display","none"),$("#packageRecommend")[0].className="startcity"))});$(document).bind("click",function(a){a=a||window.event;a=
a.target||a.srcElement;$("#flightCityPop").contains(a)||($("#flightMoreCityDiv").css("display","none"),$("#packageRecommend")[0].className="startcity")});$("#flightMoreCityDiv").bind("mousedown",function(b){b=b||window.event;b=b.target||b.srcElement;"A"===b.nodeName&&($("#packageRecommend")[0].className="startcity",a=b.getAttribute("data-szm"),$("#flightMoreCityDiv").css("display","none"),$("#flightPopSpan").html(b.innerHTML),e.request())})},refreshFlight:function(){0<$("#flight_fresh").length&&$("#flight_fresh").bind("click",
function(a){e.guessRequest(b)})},overtab:function(){$("#flight_tab").bind("mousedown",function(a){$("#flightGuessList>ul")[0]&&($("#flight_tab")[0].getElementsByTagName("span"),a=a||window.event,a=a.target||a.srcElement,"flight_tab_domestic"==a.id&&($("#flightGuessList").css("display","none"),$("#flightList").css("display","block"),$("#flightCityPop").css("display","block"),$("#flight_tab>span").removeClass("current"),$("#flight_tab>span")[1].className="current"),"flight_tab_guess"==a.id&&($("#flightGuessList").css("display",
"block"),$("#flightList").css("display","none"),$("#flightCityPop").css("display","none"),$("#flight_tab_guess").addClass("current"),$("#flight_tab_domestic").removeClass("current")))})}},e={request:function(){$.ajax(b,{cache:!0,async:!0,method:cQuery.AJAX_METHOD_POST,context:{tabid:1,dcity:a},onsuccess:function(a){a=$.parseJSON(a.responseText);e.formatHTML(a)}})},guessRequest:function(a){var b=this;$.ajax(a,{cache:!0,async:!0,method:cQuery.AJAX_METHOD_POST,context:{tabId:0,guessIndex:h},onsuccess:function(a){var d=
$.parseJSON(a.responseText);(d?b.render(d,a.responseText):($("#flight_tab_guess").css("display","none"),$("#flightGuessList").css("display","none"),$("#flightList").css("display","block"),$("#flightCityPop").css("display","block"),$("#flight_tab>span").removeClass="current",$("#flight_tab>span")[1].className="current"))}})},render:function(a,b){var c=0,c=a.length,g="total="+c.toString(),k='<span id="flightGuessPageInfo" flightGuessAmounts ={$flightGuessAmounts}></span><script type="text/plain" id="flightResponseText">{$flightGuessResult}\x3c/script>'.replaceWith({flightGuessAmounts:c,
flightGuessResult:b}),t=parseInt(c/4);h>t-1&&(h=0);for(var t=[],l=0,u=a.length;l<u;l++){var p=l+1;t[t.length]=(4>l?'<li class="likes_flight_img"><a target="_blank" href="{$url}"><div class="flight_img"><img _src="{$imgUrl}"alt="" width="204px"></div><div class="flight_name">{$departCity}&nbsp;\u2192&nbsp;{$arrvieCity}</div><div class="flight_info"><strong>{$departDate}</strong><span class="c_price">{$lowestPrice}</span>{$discount}</div><span class="b_tag">{$arrvieCity}</span></a></li>'.replaceWith({url:a[l].url+
"#ctm_ref=ctr_hp_rec_frc_"+p.toString(),imgUrl:a[l].imgUrl,departDate:a[l].adepartDate,departCity:a[l].departCityName,arrvieCity:a[l].arrvieCityName,lowestPrice:a[l].lowestPrice,discount:a[l].discount,discountSTD:a[l].discountSTD,departDateSTD:a[l].adepartDateSTD}):'<li><a target="_blank" href="{$url}"><div class="flight_name">{$departCity}&nbsp;\u2192&nbsp;{$arrvieCity}</div><div class="flight_info"><strong>{$departDate}</strong><span class="c_price">{$lowestPrice}</span>{$discount}</div></a></li>'.replaceWith({url:(8>
l?a[l].url+"#ctm_ref=ctr_hp_rec_frc_"+p.toString():a[l].url+"#ctm_ref=ctr_hp_rec_fdj_"+p.toString()),departDate:a[l].adepartDate,departCity:a[l].departCityName,arrvieCity:a[l].arrvieCityName,lowestPrice:a[l].lowestPrice,discount:a[l].discount,discountSTD:a[l].discountSTD,departDateSTD:a[l].adepartDateSTD}));g+="&dcity"+p.toString()+"="+a[l].departCity+"&acity"+p.toString()+"="+a[l].arrvieCity+"&fromtime"+p.toString()+"="+a[l].adepartDateSTD+"&discount"+p.toString()+"="+a[l].discountSTD+"&price"+p.toString()+
"="+a[l].lowestPrice}0<c&&($("#flightGuessList").html('<ul class="likes_flight_list">'+k+t.join("")+"</ul>"),$("#flightGuessList").css("display","block"),$("#flightGuessList").addClass("fade_in"),$("#flightList").css("display","none"),$("#flightCityPop").css("display","none"),$("#flight_tab_guess").addClass("current"),$("#flight_tab_guess").css("display","block"),$("#flight_tab_domestic").removeClass("current"));$("#flight_fresh").bind("click",function(a){a=$("#flightResponseText").html();h+=1;var c=
$.parseJSON(a);e.render(c,a)});e.lazyLoad();window.__bfi.push(["_tracklog","ctr.hp.rec.flt",g])},lazyLoad:function(){for(var a=$("#flightGuessList")[0].getElementsByTagName("img"),b=0,c=a.length;b<c;b++)a[b].getAttribute("_src")&&(a[b].src=a[b].getAttribute("_src"))},formatHTML:function(a){for(var b=[],c=0,e=a.length;c<e;c++)b[b.length]='<dl onclick="window.open(\'{$Url}\');">                <dt><a title="{$DepartCity}\u5230{$ArrvieCity}" onclick="return false;" href="{$Url}">{$DepartCity}-{$ArrvieCity}</a></dt>                <dd><span class="c_price">{$LowestPrice}</span>{$DepartDate}</dd>            </dl>'.replaceWith({DepartCity:a[c].departCityName,
ArrvieCity:a[c].arrvieCityName,LowestPrice:a[c].lowestPrice,DepartDate:a[c].adepartDate.replace("-","\u6708")+"\u65e5",Url:a[c].url});$("#flightList").html(b.join(""));Ctrip.Singleton.Statistic.setFlightStat()}};g.moreCity();g.refreshFlight();g.overtab();e.guessRequest(b);return{loadImg:function(){e.lazyLoad()}}}();
Ctrip.Singleton.Subscribe=function(){var a=$("#mailTxtId").regMod("notice","1.0",{name:"mailTxtId",tips:config.tip.email[3],selClass:"inputSel"}),b=$("#mailSubmitId")[0];b.disabled=!1;$("#mailSubmitId").bind("click",function(){if(a.method("isEmpty"))return Ctrip.Util.PageConfig.formValidate.method("show",{$obj:$("#mailTxtId"),data:config.tip.email[0],removeErrorClass:!0,hideEvent:"blur",isFocus:!0,isScroll:!1,position:"bm_tl"}),b.disabled=!1;if(!(/^[^@\s]+@[^@\.\s]+(\.[^@\.\s]+)+$/).test($("#mailTxtId").value()))return Ctrip.Util.PageConfig.formValidate.method("show",
{$obj:$("#mailTxtId"),data:config.tip.email[1],removeErrorClass:!0,hideEvent:"blur",isFocus:!0,isScroll:!1,position:"bm_tl"}),b.disabled=!1;b.disabled=!0;var h=escape($("#mailTxtId").value());$.ajax(config.url.mailAjaxGet,{cache:!0,async:!0,method:cQuery.AJAX_METHOD_POST,context:{oldemail:h},onsuccess:function(a){a=a.responseText;if(""!=a){$("#div_mailbook").css("display","none");$("#mail_state_sucess").css("display","block");var b="",d;if(d=document.cookie.match((/(^| )ticket_ctrip=([^;]*)(;|$)/)))b=
unescape(d[2]);""==b&&(document.getElementById("a_MySubsctribe").href="http://my.ctrip.com/subscription/UnLogin.aspx?email="+a)}}})});$("#a_back").bind("click",function(){$("#div_mailbook").css("display","block");$("#mail_state_sucess").css("display","none");b.disabled=!1;a.method("resetValue")})}();
Ctrip.Singleton.Community=function(){var a=$("#communityBtns>a"),b=$("#communityPics>li"),h=2,g,e=[],d={init:function(){for(var c=0,q=a.length;c<q;c++)(function(){var b=c;$(a[b]).bind("click",function(){clearTimeout(g);for(var a=0,c=e.length;a<c;a++)clearInterval(e[a]),e[a]=null;d.btnFocus(b);d.picFocus(b);f.init(b)})})(c);c=0;for(q=b.length;c<q;c++)(function(){var a=c;d.onmouseenter(b[a],function(){b[a].style.zIndex=h++;b[a].style.opacity=100;b[a].style.filter="alpha(opacity=100)";f.clearInte();
f.clearTime()});d.onmouseout(b[a],function(){f.init(a)})})(c)},btnFocus:function(c){a.removeClass("raiders_current");a[c].className="raiders_current"},picFocus:function(a){b[a].style.zIndex=h++;f.opacity(a,0,100)},onmouseenter:function(a,b){(document.all?a.onmouseenter=function(a){b()}:a.onmouseover=function(a){(null==a.relatedTarget?b():this!==a.relatedTarget&&20!=this.compareDocumentPosition(a.relatedTarget)&&b())})},onmouseout:function(a,b){(document.all?a.onmouseleave=b:a.onmouseout=function(a){(null==
a.relatedTarget?b():this!==a.relatedTarget&&20!=this.compareDocumentPosition(a.relatedTarget)&&b())})}},f={init:function(a){g=setTimeout(function(){a=(2===a?0:a+1);f.clearInte();d.btnFocus(a);d.picFocus(a);g=setTimeout(arguments.callee,1E4)},1E4)},opacity:function(a,d,f){b[a].style.opacity=d/100;b[a].style.filter="alpha(opacity="+d+")";e[a]=setInterval(function(){(d>=f?(b[a].style.opacity=f/100,b[a].style.filter="alpha(opacity="+f+")",clearInterval(e[a])):(b[a].style.opacity=d/100,b[a].style.filter="alpha(opacity="+
d+")"));d+=5},30)},clearInte:function(){for(var a=0,b=e.length;a<b;a++)clearInterval(e[a]),e[a]=null},clearTime:function(){clearTimeout(g);g=null}};0<$("#communityBtns").length&&0<$("#communityPics").length&&(d.init(),f.init(0))}();
Ctrip.Singleton.Public=function(){window.addfavor=function(a,b){if(-1<navigator.userAgent.toLowerCase().indexOf("msie 8"))window.external.AddToFavoritesBar(a,b,b);else try{window.external.addFavorite(a,b)}catch(c){try{window.sidebar.addPanel(b,a,"")}catch(d){if((/Chrome\/(\S+)/).test(navigator.userAgent)){var f={title:b,url:a};history.replaceState(f,b,a)}(/Safari\/(\S+)/).test(navigator.userAgent)&&(f={title:b,url:a},history.replaceState(f,b,a));alert(validateMessageConfig.other[2])}}};window.setYongAn=
function(a){var b;b=("YA"==a?"http://www.wingontravel.com":"http://www.ctrip.com");$.ajax("/home/Ajax_YongAnRecord.asp",{method:cQuery.AJAX_METHOD_POST,context:{oriURL:document.referrer,tarurl:b},escape:!1,async:!0,cache:!1,onsuccess:function(c){null!=c&&"YA"==a&&(document.location.href=b)}})};for(var a=$("#div_LvPing>ul>li>a>img"),b=0,h=a.length;b<h;b++)a[b].src=a[b].getAttribute("_src");a=$("#ad_onsaleId>a>img");b=0;for(h=a.length;b<h;b++)a[b].src=a[b].getAttribute("_src");$(window).bind("resize",
function(){"block"==document.getElementById("divChooseLanguage").style.display&&$("#divChooseLanguage").mask()});a={www:{pid:"100101",sub:["hotels","flights","vacations"]},hotels:{pid:"102001|102002|102101|102102",sub:["flights","vacations"]},flights:{pid:"101023|101027|101029|104001|104002|104003",sub:["hotels","vacations"]},vacations:{pid:"10300100|10300101|10300102|10300103|10300104|10300105|10300106|10300107|10300200|10310303",sub:["hotels","flights"]}};try{var g=(document.domain||"").match((/^([^.]+)(\.(.+)?ctrip(travel||corp)?\.com(\.hk)?)$/)),
e=g[1],d=g[2],f=document.getElementById("page_id");if(!a[e]||!f||-1==a[e].pid.indexOf(f.value))return!1;var c=a[e].sub;if(c)for(var b=0,q=c.length;b<q;b++)(new Image).src="http://"+c[b]+d+"/pic_alpha.gif?t="+parseInt(new Date/60,10)}catch(k){}}();Ctrip.Singleton.DomReady=function(){}();var checkForFoldYc={key:!0};
$("#seo_more").bind("click",function(){(checkForFoldYc.key?($(this).parentNode().parentNode().parentNode().find(".seo_hot").addClass("sta_unfold"),checkForFoldYc.key=!1):($(this).parentNode().parentNode().parentNode().find(".seo_hot").removeClass("sta_unfold"),checkForFoldYc.key=!0))});$(".seo_hot").removeClass("sta_unfold");
Ctrip.Singleton.Language=function(){var a=new Date;a.setDate(a.getDate()+7);var b=(document.domain||"").match((/^([^.]+)(\.(.+)?ctrip(travel||corp)?\.com(\.hk)?)$/))[2].replace(".hk","");$(".cui_lang_en").bind("click",function(d){d=d||window.event;d=(d.target||d.srcElement).className.replace("cui_lang","ctrip");cQuery.cookie.set("Customer","HAL",d,{expires:a,domain:b});cQuery.cookie.set("_ctm_t",null,"ctrip",{domain:b})});for(var h=$(".cui_lang_list > a"),g=0,e=h.length;g<e;g++)(function(){$(h[g]).bind("click",
function(d){d=d||window.event;d=(d.target||d.srcElement).className.replace("cui_lang","ctrip");cQuery.cookie.set("Customer","HAL",d,{expires:a,domain:b});cQuery.cookie.set("_ctm_t",null,"ctrip",{domain:b})})})(g);for(var d=$("#cui_lang_bottom > a"),g=0,e=d.length;g<e;g++)(function(){$(d[g]).bind("click",function(d){d=d||window.event;d=(d.target||d.srcElement).className.replace("cui_lang","ctrip");cQuery.cookie.set("Customer","HAL",d,{expires:a,domain:b});cQuery.cookie.set("_ctm_t",null,"ctrip",{domain:b})})})(g);
$("#a_unmask").bind("click",function(a){a=new Date;a.setDate(a.getDate()+7);cQuery.cookie.set("Customer","HAL","ctrip_gb",{expires:a,domain:b});$("#divChooseLanguage").unmask()});void 0!=$("#pad_close")&&$("#pad_close").bind("click",function(a){a=new Date;a.setDate(a.getDate()+1);cQuery.cookie.set("CustomerDevice","PAD","hide",{expires:a,domain:b});$("#pad_pop").css("display","none")});$("#a_HK").bind("click",function(a){a=new Date;a.setDate(a.getDate()+90);cQuery.cookie.set("Customer","HAL","ctrip_big5",
{expires:a,domain:b});document.location.href="http://www.ctrip.com.hk/"});$("#a_CN").bind("click",function(a){a=new Date;a.setDate(a.getDate()+90);cQuery.cookie.set("Customer","HAL","ctrip_gb",{expires:a,domain:b});$("#divChooseLanguage").unmask()});e=window.location.search.substr(1).match((/(^|&)lan=([^&]*)(&|$)/i));null!=e&&"gb"==unescape(e[2])&&cQuery.cookie.set("Customer","HAL","ctrip_gb",{expires:a,domain:b})}();
$(window).bind("load",function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="http://mcc.chinauma.net/static/scripts/p.js?id=208&w=980&h=90&sl=1&delay=5";a.setAttribute("zp_type","1");a.setAttribute("id","zp_script_208");document.getElementById("googlead").appendChild(a);$.ajax(config.url.popAjax,{async:!0,method:cQuery.AJAX_METHOD_POST,onsuccess:function(a){a=$.parseJSON(a.responseText);var h=new Date;""!==a[0].trim()&&($("#qqcaibei").html(a[0]),$("#qqcaibei").css("display",
"block"),$("#pop_click1").bind("click",function(){this.parentNode.style.display="none"}));if(""!==a[1].trim()){$("#popup").html(a[1]);var g=$("#popStart").value(),e=$("#popEnd").value(),d=$("#uid").value();(h>=new Date(g.replace((/-/g),"/"))&&h<=new Date(e.replace((/-/g),"/"))||"wwwwww"==d)&&"1"!==cQuery.cookie.get("popup")&&(document.getElementById("popup").style.display="block",$("#pop_click2").bind("click",function(){this.parentNode.style.display="none";cQuery.cookie.set("popup",null,"1",{expires:30,
domain:document.domain})}))}""!==a[2].trim()&&($("#bindemail").html(a[2]),document.getElementById("bindemail").style.display="block",$("#email_close").bind("click",function(){this.parentNode.style.display="none"}));4==a.length&&""!==a[3].trim()&&($("#accountSec").html(a[3]),document.getElementById("accountSec").style.display="block",$("#account_sec_close").bind("click",function(){this.parentNode.style.display="none"}))}});"1"==$("#hongkongMask").value()&&$("#hongkong_customer").mask();document.getElementById("padTipId")&&
$($("#padTipId>a")[1]).bind("click",function(){$("#padTipId").css("display","none");var a={ispad:"true"},h=[],g;for(g in a){var e=(null===a[g]?"":escape(a[g]));h.push(g+"="+e)}a=new Date;a.setMonth(a.getMonth()+1);document.cookie=h.join("&")+"; expires="+a.toGMTString()+"; domain=ctrip.com;"})});
