/*
 * File: TreeGridPanelTopToolBar.ui.js
 * Date: Fri Jul 23 2010 11:31:12 GMT+0800 (China Standard Time)
 * 
 * This file was generated by Ext Designer version xds-1.0.1.0c.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

TreeGridPanelToolBar = Ext.extend(Ext.Panel, {
    title: '',
	id:'treegridpaneltoolbar',
    layout: 'hbox',
    border: false,
	cls:'panel-bg-grid-panel',
    initComponent: function() {
        this.items = [
            {
                xtype: 'button',
                text: 'Delete Selected',
				cls:'btn btn-delete'
            },
            {
                xtype: 'button',
                text: 'Archived Selected',
				cls:'btn btn-archived'
            },
            {
                xtype: 'displayfield',
                fieldLabel: 'Label',
                value: '<p class="displayfield-font-grid-panel-toolbar">No contacts selected</p>'
            },
            {
                xtype: 'panel',
                title: '',
                flex: 1,
				items:[				
					new uxPaking({
						totalData:400,
    					pageData:20,
    					showItem:5							
					})					
				],
                border: false
            }
        ];
        TreeGridPanelTopToolBar.superclass.initComponent.call(this);
    }
});
